// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

public interface CatMessageDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CatMessageData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 period = 1;</code>
   */
  long getPeriod();
}
