// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

/**
 * Protobuf type {@code CatMessageRequest}
 */
public  final class CatMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CatMessageRequest)
    CatMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CatMessageRequest.newBuilder() to construct.
  private CatMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CatMessageRequest() {
    period_ = 0L;
    dataList_ = java.util.Collections.emptyList();
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CatMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            period_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              dataList_ = new java.util.ArrayList<com.dianping.cat.message.facade.proto.CatMessageData>();
              mutable_bitField0_ |= 0x00000002;
            }
            dataList_.add(
                input.readMessage(com.dianping.cat.message.facade.proto.CatMessageData.parser(), extensionRegistry));
            break;
          }
          case 24: {

            timestamp_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        dataList_ = java.util.Collections.unmodifiableList(dataList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dianping.cat.message.facade.proto.MessageFacadeProto.internal_static_CatMessageRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dianping.cat.message.facade.proto.MessageFacadeProto.internal_static_CatMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dianping.cat.message.facade.proto.CatMessageRequest.class, com.dianping.cat.message.facade.proto.CatMessageRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PERIOD_FIELD_NUMBER = 1;
  private long period_;
  /**
   * <code>int64 period = 1;</code>
   */
  public long getPeriod() {
    return period_;
  }

  public static final int DATA_LIST_FIELD_NUMBER = 2;
  private java.util.List<com.dianping.cat.message.facade.proto.CatMessageData> dataList_;
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  public java.util.List<com.dianping.cat.message.facade.proto.CatMessageData> getDataListList() {
    return dataList_;
  }
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  public java.util.List<? extends com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder> 
      getDataListOrBuilderList() {
    return dataList_;
  }
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  public int getDataListCount() {
    return dataList_.size();
  }
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  public com.dianping.cat.message.facade.proto.CatMessageData getDataList(int index) {
    return dataList_.get(index);
  }
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  public com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder getDataListOrBuilder(
      int index) {
    return dataList_.get(index);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (period_ != 0L) {
      output.writeInt64(1, period_);
    }
    for (int i = 0; i < dataList_.size(); i++) {
      output.writeMessage(2, dataList_.get(i));
    }
    if (timestamp_ != 0L) {
      output.writeInt64(3, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (period_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, period_);
    }
    for (int i = 0; i < dataList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, dataList_.get(i));
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dianping.cat.message.facade.proto.CatMessageRequest)) {
      return super.equals(obj);
    }
    com.dianping.cat.message.facade.proto.CatMessageRequest other = (com.dianping.cat.message.facade.proto.CatMessageRequest) obj;

    boolean result = true;
    result = result && (getPeriod()
        == other.getPeriod());
    result = result && getDataListList()
        .equals(other.getDataListList());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPeriod());
    if (getDataListCount() > 0) {
      hash = (37 * hash) + DATA_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getDataListList().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dianping.cat.message.facade.proto.CatMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dianping.cat.message.facade.proto.CatMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CatMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CatMessageRequest)
      com.dianping.cat.message.facade.proto.CatMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dianping.cat.message.facade.proto.MessageFacadeProto.internal_static_CatMessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dianping.cat.message.facade.proto.MessageFacadeProto.internal_static_CatMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dianping.cat.message.facade.proto.CatMessageRequest.class, com.dianping.cat.message.facade.proto.CatMessageRequest.Builder.class);
    }

    // Construct using com.dianping.cat.message.facade.proto.CatMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      period_ = 0L;

      if (dataListBuilder_ == null) {
        dataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        dataListBuilder_.clear();
      }
      timestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dianping.cat.message.facade.proto.MessageFacadeProto.internal_static_CatMessageRequest_descriptor;
    }

    public com.dianping.cat.message.facade.proto.CatMessageRequest getDefaultInstanceForType() {
      return com.dianping.cat.message.facade.proto.CatMessageRequest.getDefaultInstance();
    }

    public com.dianping.cat.message.facade.proto.CatMessageRequest build() {
      com.dianping.cat.message.facade.proto.CatMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dianping.cat.message.facade.proto.CatMessageRequest buildPartial() {
      com.dianping.cat.message.facade.proto.CatMessageRequest result = new com.dianping.cat.message.facade.proto.CatMessageRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.period_ = period_;
      if (dataListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dataList_ = java.util.Collections.unmodifiableList(dataList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dataList_ = dataList_;
      } else {
        result.dataList_ = dataListBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dianping.cat.message.facade.proto.CatMessageRequest) {
        return mergeFrom((com.dianping.cat.message.facade.proto.CatMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dianping.cat.message.facade.proto.CatMessageRequest other) {
      if (other == com.dianping.cat.message.facade.proto.CatMessageRequest.getDefaultInstance()) return this;
      if (other.getPeriod() != 0L) {
        setPeriod(other.getPeriod());
      }
      if (dataListBuilder_ == null) {
        if (!other.dataList_.isEmpty()) {
          if (dataList_.isEmpty()) {
            dataList_ = other.dataList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataListIsMutable();
            dataList_.addAll(other.dataList_);
          }
          onChanged();
        }
      } else {
        if (!other.dataList_.isEmpty()) {
          if (dataListBuilder_.isEmpty()) {
            dataListBuilder_.dispose();
            dataListBuilder_ = null;
            dataList_ = other.dataList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            dataListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDataListFieldBuilder() : null;
          } else {
            dataListBuilder_.addAllMessages(other.dataList_);
          }
        }
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dianping.cat.message.facade.proto.CatMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dianping.cat.message.facade.proto.CatMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long period_ ;
    /**
     * <code>int64 period = 1;</code>
     */
    public long getPeriod() {
      return period_;
    }
    /**
     * <code>int64 period = 1;</code>
     */
    public Builder setPeriod(long value) {
      
      period_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 period = 1;</code>
     */
    public Builder clearPeriod() {
      
      period_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.dianping.cat.message.facade.proto.CatMessageData> dataList_ =
      java.util.Collections.emptyList();
    private void ensureDataListIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        dataList_ = new java.util.ArrayList<com.dianping.cat.message.facade.proto.CatMessageData>(dataList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dianping.cat.message.facade.proto.CatMessageData, com.dianping.cat.message.facade.proto.CatMessageData.Builder, com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder> dataListBuilder_;

    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public java.util.List<com.dianping.cat.message.facade.proto.CatMessageData> getDataListList() {
      if (dataListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dataList_);
      } else {
        return dataListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public int getDataListCount() {
      if (dataListBuilder_ == null) {
        return dataList_.size();
      } else {
        return dataListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public com.dianping.cat.message.facade.proto.CatMessageData getDataList(int index) {
      if (dataListBuilder_ == null) {
        return dataList_.get(index);
      } else {
        return dataListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder setDataList(
        int index, com.dianping.cat.message.facade.proto.CatMessageData value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.set(index, value);
        onChanged();
      } else {
        dataListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder setDataList(
        int index, com.dianping.cat.message.facade.proto.CatMessageData.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.set(index, builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder addDataList(com.dianping.cat.message.facade.proto.CatMessageData value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.add(value);
        onChanged();
      } else {
        dataListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder addDataList(
        int index, com.dianping.cat.message.facade.proto.CatMessageData value) {
      if (dataListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDataListIsMutable();
        dataList_.add(index, value);
        onChanged();
      } else {
        dataListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder addDataList(
        com.dianping.cat.message.facade.proto.CatMessageData.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.add(builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder addDataList(
        int index, com.dianping.cat.message.facade.proto.CatMessageData.Builder builderForValue) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.add(index, builderForValue.build());
        onChanged();
      } else {
        dataListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder addAllDataList(
        java.lang.Iterable<? extends com.dianping.cat.message.facade.proto.CatMessageData> values) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataList_);
        onChanged();
      } else {
        dataListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder clearDataList() {
      if (dataListBuilder_ == null) {
        dataList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        dataListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public Builder removeDataList(int index) {
      if (dataListBuilder_ == null) {
        ensureDataListIsMutable();
        dataList_.remove(index);
        onChanged();
      } else {
        dataListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public com.dianping.cat.message.facade.proto.CatMessageData.Builder getDataListBuilder(
        int index) {
      return getDataListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder getDataListOrBuilder(
        int index) {
      if (dataListBuilder_ == null) {
        return dataList_.get(index);  } else {
        return dataListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public java.util.List<? extends com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder> 
         getDataListOrBuilderList() {
      if (dataListBuilder_ != null) {
        return dataListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dataList_);
      }
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public com.dianping.cat.message.facade.proto.CatMessageData.Builder addDataListBuilder() {
      return getDataListFieldBuilder().addBuilder(
          com.dianping.cat.message.facade.proto.CatMessageData.getDefaultInstance());
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public com.dianping.cat.message.facade.proto.CatMessageData.Builder addDataListBuilder(
        int index) {
      return getDataListFieldBuilder().addBuilder(
          index, com.dianping.cat.message.facade.proto.CatMessageData.getDefaultInstance());
    }
    /**
     * <code>repeated .CatMessageData data_list = 2;</code>
     */
    public java.util.List<com.dianping.cat.message.facade.proto.CatMessageData.Builder> 
         getDataListBuilderList() {
      return getDataListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dianping.cat.message.facade.proto.CatMessageData, com.dianping.cat.message.facade.proto.CatMessageData.Builder, com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder> 
        getDataListFieldBuilder() {
      if (dataListBuilder_ == null) {
        dataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dianping.cat.message.facade.proto.CatMessageData, com.dianping.cat.message.facade.proto.CatMessageData.Builder, com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder>(
                dataList_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        dataList_ = null;
      }
      return dataListBuilder_;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CatMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:CatMessageRequest)
  private static final com.dianping.cat.message.facade.proto.CatMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dianping.cat.message.facade.proto.CatMessageRequest();
  }

  public static com.dianping.cat.message.facade.proto.CatMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CatMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<CatMessageRequest>() {
    public CatMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CatMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CatMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CatMessageRequest> getParserForType() {
    return PARSER;
  }

  public com.dianping.cat.message.facade.proto.CatMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

