// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

public interface CatMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CatMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
