// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

public interface CatMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CatMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 period = 1;</code>
   */
  long getPeriod();

  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  java.util.List<com.dianping.cat.message.facade.proto.CatMessageData> 
      getDataListList();
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  com.dianping.cat.message.facade.proto.CatMessageData getDataList(int index);
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  int getDataListCount();
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  java.util.List<? extends com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder> 
      getDataListOrBuilderList();
  /**
   * <code>repeated .CatMessageData data_list = 2;</code>
   */
  com.dianping.cat.message.facade.proto.CatMessageDataOrBuilder getDataListOrBuilder(
      int index);

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
