// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

public interface ChannelHealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelHealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enable = 1;</code>
   */
  boolean getEnable();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
