// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_facade.proto

package com.dianping.cat.message.facade.proto;

public interface ChannelHealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelHealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string client_ip = 1;</code>
   */
  java.lang.String getClientIp();
  /**
   * <code>string client_ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIpBytes();
}
